// 洛克王国攻略站 · 公共数据文件（30只精灵）
const pokemonData = [
    // ===== 1-10：原数据保持不变 =====
    { id:1, name:"火花", number:1, type:["火"], stage:"基础", race:{hp:50, atk:55, def:45, spa:60, spd:50, spe:65}, total:325, catch:"初始伙伴选择 / 火山脚下遇见", skills:["火苗","烟幕","火花踢","蓄能焰火"], evolution:{ next:"烈火兽", method:"等级16进化" }, description:"热情而忠诚的火焰精灵，身上的火焰会随着心情变化。新手训练家最可靠的伙伴之一。" },
    { id:2, name:"水蓝", number:4, type:["水"], stage:"基础", race:{hp:55, atk:45, def:60, spa:65, spd:55, spe:45}, total:325, catch:"初始伙伴选择 / 湖泊浅滩", skills:["水枪","泡沫","水流环","求雨"], evolution:{ next:"浪涛兽", method:"等级16进化" }, description:"性格温和的水系精灵，能净化水质。在水中移动时几乎不发出声音。" },
    { id:3, name:"翠芽", number:7, type:["草"], stage:"基础", race:{hp:50, atk:50, def:65, spa:60, spd:60, spe:40}, total:325, catch:"初始伙伴选择 / 密林小径", skills:["飞叶快刀","光合作用","藤鞭","麻痹粉"], evolution:{ next:"翠藤精", method:"等级16进化" }, description:"头上嫩芽会预知天气的草系精灵，最喜欢温暖有阳光的地方。" },
    { id:4, name:"叮叮恶魔", number:25, type:["恶","翼"], stage:"最终", race:{hp:80, atk:120, def:70, spa:90, spd:65, spe:110}, total:535, catch:"暗影森林深处 · 夜晚概率出现（稀有）", skills:["暗袭","飞空斩","恶魔契约","诡计","暗影球","空气斩"], evolution:{ prev:"叮叮蝠", method:"使用暗之石进化" }, description:"栖息在暗影森林深处的恶翼双属性精灵，速度极快，擅长先手攻击。" },
    { id:5, name:"独角兽", number:12, type:["龙","水"], stage:"一阶", race:{hp:100, atk:80, def:100, spa:90, spd:90, spe:60}, total:520, catch:"圣湖遗迹 · 雨天概率出现", skills:["水枪","龙息","治愈波动","光之壁","龙之舞"], evolution:{ next:"圣角天马", method:"等级40进化" }, description:"拥有龙族血统的高贵精灵，角上的光芒能够治愈伤痛。" },
    { id:6, name:"冰布丁", number:44, type:["冰"], stage:"最终", race:{hp:80, atk:50, def:60, spa:110, spd:100, spe:90}, total:490, catch:"极冻雪原 · 任何时段", skills:["冰冻之风","极光幕","暴风雪","冰雹","绝对零度"], evolution:{ prev:"冰团子", method:"携带不融冰升级进化" }, description:"身体柔软如布丁，却能释放极寒气息。在雪原中几乎与环境融为一体。" },
    { id:7, name:"暗翼兽", number:78, type:["恶","翼"], stage:"一阶", race:{hp:65, atk:100, def:55, spa:70, spd:55, spe:130}, total:475, catch:"迷失之塔顶层 · 夜晚概率出现", skills:["暗袭","翅膀攻击","高速移动","黑夜魔影"], evolution:{ next:"暗翼龙王", method:"等级36进化" }, description:"在黑暗中无声飞行的掠食者，速度极快，猎物难以察觉它的靠近。" },
    { id:8, name:"石甲龟", number:33, type:["岩石","地面"], stage:"基础", race:{hp:70, atk:65, def:100, spa:40, spd:55, spe:25}, total:355, catch:"岩石洞穴 · 全天出现", skills:["落石","变硬","地震","守住"], evolution:{ next:"岩甲巨龟", method:"等级28进化" }, description:"背上的岩石甲壳坚硬无比，遇到危险会缩进壳中，防御力惊人。" },
    { id:9, name:"电击鼠", number:18, type:["电"], stage:"基础", race:{hp:45, atk:40, def:35, spa:70, spd:40, spe:95}, total:325, catch:"发电厂废墟 · 晴天出现", skills:["电击","电光一闪","十万伏特","电磁波"], evolution:{ next:"雷电鼠王", method:"使用雷之石进化" }, description:"脸颊的电气袋能储存电力，速度极快，常被训练家用来快速清场。" },
    { id:10, name:"幽灵娃娃", number:55, type:["幽灵"], stage:"一阶", race:{hp:60, atk:45, def:50, spa:100, spd:85, spe:70}, total:410, catch:"废弃洋馆 · 夜晚限定", skills:["暗影球","诅咒","催眠术","食梦"], evolution:{ prev:"鬼火", method:"亲密度足够时升级进化" }, description:"喜欢恶作剧的幽灵精灵，据说在午夜洋馆中会发出奇怪的笑声。" },

    // ===== 11-30：新增精灵 =====
    { id:11, name:"烈火兽", number:2, type:["火"], stage:"一阶", race:{hp:70, atk:80, def:60, spa:85, spd:65, spe:90}, total:450, catch:"火花16级进化", skills:["火焰轮","喷射火焰","火焰牙","蓄能焰火"], evolution:{ prev:"火花", next:"烈焰战将", method:"等级36进化" }, description:"火花的进化形态，浑身燃烧着炽热的火焰，奔跑时火星四溅。" },
    { id:12, name:"浪涛兽", number:5, type:["水"], stage:"一阶", race:{hp:75, atk:60, def:80, spa:90, spd:75, spe:60}, total:440, catch:"水蓝16级进化", skills:["水流尾","冲浪","水流环","求雨"], evolution:{ prev:"水蓝", next:"深海霸主", method:"等级36进化" }, description:"水蓝的进化形态，能掀起巨浪，保护同伴免受攻击。" },
    { id:13, name:"翠藤精", number:8, type:["草"], stage:"一阶", race:{hp:70, atk:65, def:90, spa:80, spd:85, spe:55}, total:445, catch:"翠芽16级进化", skills:["藤鞭强击","叶片风暴","寄生种子","光合作用"], evolution:{ prev:"翠芽", next:"荆棘花仙", method:"等级36进化" }, description:"翠芽的进化形态，挥舞坚韧的藤蔓，能治愈自己和同伴。" },
    { id:14, name:"圣角天马", number:13, type:["龙","水"], stage:"最终", race:{hp:120, atk:90, def:110, spa:105, spd:100, spe:75}, total:600, catch:"独角兽40级进化", skills:["龙之波动","水之誓约","治愈波动","龙之舞"], evolution:{ prev:"独角兽", method:"等级40进化" }, description:"独角兽的最终形态，头上的圣角能驱散邪恶，被誉为圣湖的守护者。" },
    { id:15, name:"暗翼龙王", number:79, type:["恶","翼"], stage:"最终", race:{hp:80, atk:125, def:70, spa:85, spd:70, spe:140}, total:570, catch:"暗翼兽36级进化", skills:["暗影爪","神鸟猛击","龙之舞","诡计"], evolution:{ prev:"暗翼兽", method:"等级36进化" }, description:"暗翼兽的进化形态，拥有龙族血统，在黑夜中无声猎杀。" },
    { id:16, name:"冰团子", number:43, type:["冰"], stage:"基础", race:{hp:60, atk:35, def:45, spa:75, spd:65, spe:55}, total:335, catch:"极冻雪原 · 暴风雪天气出现", skills:["冰冻之风","细雪","变硬","冰雹"], evolution:{ next:"冰布丁", method:"携带不融冰升级进化" }, description:"像糯米团子一样的冰系精灵，身体总是冷冰冰的，性格胆小。" },
    { id:17, name:"岩甲巨龟", number:34, type:["岩石","地面"], stage:"最终", race:{hp:100, atk:95, def:140, spa:55, spd:80, spe:30}, total:500, catch:"石甲龟28级进化", skills:["岩石炮","地震","铁壁","守住"], evolution:{ prev:"石甲龟", method:"等级28进化" }, description:"石甲龟的进化形态，甲壳坚硬如山，能抵御绝大多数物理攻击。" },
    { id:18, name:"雷电鼠王", number:19, type:["电"], stage:"最终", race:{hp:65, atk:55, def:50, spa:105, spd:60, spe:125}, total:460, catch:"电击鼠使用雷之石进化", skills:["打雷","伏特替换","电气场地","蹭蹭脸颊"], evolution:{ prev:"电击鼠", method:"使用雷之石进化" }, description:"电击鼠的进化形态，速度极快，全身被雷电包裹，性格好战。" },
    { id:19, name:"鬼火", number:54, type:["幽灵"], stage:"基础", race:{hp:40, atk:35, def:35, spa:70, spd:45, spe:55}, total:280, catch:"废弃洋馆 · 夜晚出现", skills:["暗影球","惊吓","奇异之光","黑夜魔影"], evolution:{ next:"幽灵娃娃", method:"亲密度足够时升级进化" }, description:"一团幽幽的鬼火，喜欢在无人洋馆中游荡，靠近时会感到寒意。" },
    { id:20, name:"叮叮蝠", number:24, type:["恶","翼"], stage:"基础", race:{hp:55, atk:80, def:50, spa:55, spd:45, spe:95}, total:380, catch:"暗影森林 · 夜晚出现", skills:["暗袭","超声波","翅膀攻击","高速移动"], evolution:{ next:"叮叮恶魔", method:"使用暗之石进化" }, description:"倒挂在暗影森林的蝙蝠精灵，能发出干扰对手的声波。" },
    { id:21, name:"格斗小子", number:61, type:["格斗"], stage:"基础", race:{hp:65, atk:85, def:55, spa:30, spd:40, spe:70}, total:345, catch:"训练场 · 全天出现", skills:["空手劈","下盘踢","健美","看穿"], evolution:{ next:"武斗大师", method:"等级30进化" }, description:"热爱格斗的小精灵，每天都会对着木桩练习拳法。" },
    { id:22, name:"武斗大师", number:62, type:["格斗"], stage:"一阶", race:{hp:85, atk:115, def:75, spa:40, spd:60, spe:85}, total:460, catch:"格斗小子30级进化", skills:["近身战","飞膝踢","健美","快速防守"], evolution:{ prev:"格斗小子", next:"武圣", method:"等级48进化" }, description:"格斗小子的进化形态，拳风凌厉，能劈开岩石。" },
    { id:23, name:"毒尾蝎", number:70, type:["毒","虫"], stage:"基础", race:{hp:50, atk:70, def:65, spa:45, spd:55, spe:60}, total:345, catch:"毒雾沼泽 · 全天出现", skills:["毒针","虫咬","剧毒","毒菱"], evolution:{ next:"毒刺巨蝎", method:"等级28进化" }, description:"栖息在沼泽的毒蝎精灵，尾部的毒针能让对手麻痹。" },
    { id:24, name:"毒刺巨蝎", number:71, type:["毒","虫"], stage:"一阶", race:{hp:70, atk:100, def:90, spa:55, spd:75, spe:80}, total:470, catch:"毒尾蝎28级进化", skills:["十字毒刃","致命针刺","毒液冲击","剑舞"], evolution:{ prev:"毒尾蝎", next:"毒蝎王", method:"等级42进化" }, description:"毒尾蝎的进化形态，巨大的毒刺一击就能让大型精灵倒下。" },
    { id:25, name:"小钢甲", number:80, type:["钢"], stage:"基础", race:{hp:60, atk:55, def:90, spa:35, spd:60, spe:30}, total:330, catch:"矿洞深处 · 全天出现", skills:["金属爪","铁壁","陀螺球","铁头"], evolution:{ next:"钢铁战甲", method:"等级32进化" }, description:"全身覆盖着钢铁外壳的小精灵，行动缓慢但防御力出众。" },
    { id:26, name:"钢铁战甲", number:81, type:["钢"], stage:"一阶", race:{hp:85, atk:80, def:130, spa:45, spd:85, spe:35}, total:460, catch:"小钢甲32级进化", skills:["重磅冲撞","铁壁","金属音","隐形岩"], evolution:{ prev:"小钢甲", next:"钢甲暴龙", method:"等级50进化" }, description:"小钢甲的进化形态，厚重的钢甲能反弹敌人的攻击。" },
    { id:27, name:"鸣蝉", number:88, type:["虫","草"], stage:"基础", race:{hp:45, atk:40, def:50, spa:75, spd:60, spe:65}, total:335, catch:"碧绿丛林 · 晴天出现", skills:["虫鸣","魔法叶","光合作用","麻痹粉"], evolution:{ next:"翠翼蝉", method:"等级22进化" }, description:"藏在树梢间的蝉精灵，鸣叫声能让人心神宁静。" },
    { id:28, name:"翠翼蝉", number:89, type:["虫","草"], stage:"最终", race:{hp:65, atk:50, def:70, spa:110, spd:85, spe:100}, total:480, catch:"鸣蝉22级进化", skills:["虫鸣","飞叶风暴","蝶舞","终极吸取"], evolution:{ prev:"鸣蝉", method:"等级22进化" }, description:"鸣蝉的进化形态，翠绿的薄翼能反射日光，是森林的守护者。" },
    { id:29, name:"三头地鼠", number:95, type:["地面"], stage:"基础", race:{hp:55, atk:80, def:45, spa:30, spd:40, spe:80}, total:330, catch:"干燥沙地 · 全天出现", skills:["挖洞","地震","沙暴","磨爪"], evolution:{ next:"多头地龙", method:"等级33进化" }, description:"三只地鼠一起行动，挖洞速度极快，能在沙地中瞬间消失。" },
    { id:30, name:"幻光蝶", number:100, type:["虫","超能力"], stage:"最终", race:{hp:70, atk:50, def:55, spa:120, spd:80, spe:115}, total:490, catch:"幻光森林 · 夜晚出现（稀有）", skills:["幻象光线","虫鸣","催眠粉","冥想"], evolution:{ prev:"幻光蛹", method:"亲密度足够时进化" }, description:"翅膀散发七彩光芒的稀有精灵，据说看到它的人会获得好运。" }
];
